name: Buildah Build Image Snippet
on: [push]

env:
  IMAGE_NAME: simple-restapp-image
  IMAGE_TAG: v1

jobs:
  build-image:
    name: Build image without Containerfile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: mvn package

    - name: Build Image
      uses: redhat-actions/buildah-build@v2
      with:
        base-image: docker.io/fabric8/java-alpine-openjdk11-jre
        image: '$IMAGE_NAME'
        tags: '$IMAGE_TAG'
        content: |
          target/simpleRestApp-0.0.1-SNAPSHOT.jar
        entrypoint: java -jar simpleRestApp-0.0.1-SNAPSHOT.jar
        port: 8080

      # Check if image is build
    - name: Check images created
      run: buildah images | grep '$IMAGE_NAME'
